// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvK6-DCS9Do_PNkl0tV7eE6Jp8L8KaOlw',
    appId: '1:700095714481:web:26dadbaf797f2cf8513e90',
    messagingSenderId: '700095714481',
    projectId: 'jooders-d8330',
    authDomain: 'jooders-d8330.firebaseapp.com',
    storageBucket: 'jooders-d8330.appspot.com',
    measurementId: 'G-G6F9TQMMHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGp1tPZnzX_1vmPq75tjggzYNWnHUGe0A',
    appId: '1:700095714481:android:6255bfc78f126686513e90',
    messagingSenderId: '700095714481',
    projectId: 'jooders-d8330',
    storageBucket: 'jooders-d8330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnq6Apb0gbBTP8Nq6tSxRwVIrgnqpaugw',
    appId: '1:700095714481:ios:c7f90bae60959ab3513e90',
    messagingSenderId: '700095714481',
    projectId: 'jooders-d8330',
    storageBucket: 'jooders-d8330.appspot.com',
    iosBundleId: 'com.airjood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnq6Apb0gbBTP8Nq6tSxRwVIrgnqpaugw',
    appId: '1:700095714481:ios:dcc1ec19e432ab29513e90',
    messagingSenderId: '700095714481',
    projectId: 'jooders-d8330',
    storageBucket: 'jooders-d8330.appspot.com',
    iosBundleId: 'com.example.airjood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvK6-DCS9Do_PNkl0tV7eE6Jp8L8KaOlw',
    appId: '1:700095714481:web:977918fdadf0765a513e90',
    messagingSenderId: '700095714481',
    projectId: 'jooders-d8330',
    authDomain: 'jooders-d8330.firebaseapp.com',
    storageBucket: 'jooders-d8330.appspot.com',
    measurementId: 'G-92S5S6VV07',
  );

}