// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJiui3ZT1x-WiI9k12JLvoKaOgLjAn_g',
    appId: '1:887270465899:web:5e0935278a55d4960bec2e',
    messagingSenderId: '887270465899',
    projectId: 'airjood',
    authDomain: 'airjood.firebaseapp.com',
    storageBucket: 'airjood.appspot.com',
    measurementId: 'G-2VW971NTPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTkbNzmGKOnMcWzHFRzxvAX1-j4l69ao',
    appId: '1:887270465899:android:a2d2f19a1706014d0bec2e',
    messagingSenderId: '887270465899',
    projectId: 'airjood',
    storageBucket: 'airjood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjQHhuEfPRzy53IYiN30mADLyne-tPdo',
    appId: '1:887270465899:ios:31b7ae6464d11dcd0bec2e',
    messagingSenderId: '887270465899',
    projectId: 'airjood',
    storageBucket: 'airjood.appspot.com',
    iosBundleId: 'com.example.airjood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjQHhuEfPRzy53IYiN30mADLyne-tPdo',
    appId: '1:887270465899:ios:32221b186b1163c80bec2e',
    messagingSenderId: '887270465899',
    projectId: 'airjood',
    storageBucket: 'airjood.appspot.com',
    iosBundleId: 'com.example.airjood.RunnerTests',
  );
}
